import{i as f}from"./assets/vendor-iVKk4foX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))d(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function o(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(s){if(s.ep)return;s.ep=!0;const n=o(s);fetch(s.href,n)}})();const L=e=>{f.error({iconUrl:"./img/bi_x-octagon.svg",position:"topRight",progressBarColor:"#B51B1B",message:e,messageColor:"#FAFAFB",backgroundColor:"#EF4040"})},u=e=>{f.error({iconUrl:"/img/bi_check2-circle.svg",position:"topRight",progressBarColor:"#326101",message:e,messageColor:"#FAFAFB",backgroundColor:"#59A10D"})},p=e=>{f.error({iconUrl:"./img/bi_exclamation-triangle.svg",position:"topRight",progressBarColor:"#BB7B10",message:e,messageColor:"#FAFAFB",backgroundColor:"#FFA000"})},l=e=>{try{return JSON.parse(localStorage.getItem(e))||[]}catch(t){throw console.log("Something went wrong with getting all nodes!"),t}},h=(e,t)=>{try{localStorage.setItem(e,JSON.stringify(t))}catch(o){throw console.log("Something went wrong with getting all nodes!"),o}},r={headerButtons:document.querySelector(".header-btns"),modalOverlay:document.querySelector(".modal-overlay"),modalForm:document.querySelector(".modal-form"),nodesList:document.querySelector(".nodes-list"),searchForm:document.querySelector(".search-form"),loader:document.querySelector(".loader")},m=()=>{r.loader.classList.add("is-loading")},g=()=>{r.loader.classList.remove("is-loading")},F=({id:e,title:t,message:o})=>`
    <li class="nodes-item" data-id="${e}">
        <h3 class="nodes-item-title" data-title="${t}">${t}</h3>
        <p class="nodes-item-description" data-message="${o}">${o}</p>
        <div class="nodes-item-btns">
          <button class="edit-node-btn" type="button" id="editNodeBtn">Edit</button>
          <button class="delete-node-btn" type="button" id="deleteNodeBtn">Delete</button>
        </div>
    </li>
  `,i=e=>{const t=e.map(F).join("");r.nodesList.innerHTML=t},b=e=>{e.preventDefault();const t=e.target.elements,o=t.nodeInput.value.trim(),d=t.nodeTextarea.value.trim();if(!o||!d){p("Fill all fields");return}const s=l("userNodes")||0,n={id:++s.length,title:o,message:d},a=l("userNodes")||[];a.unshift(n),h("userNodes",a),m(),setTimeout(()=>{u("You added new Node!"),i(a),g()},200),c()},v=e=>{e.target===e.currentTarget&&c(),e.target.matches("#modalCloseBtn")&&c()},N=e=>{e.key==="Escape"&&c()},c=()=>{r.modalOverlay.classList.remove("is-open"),document.removeEventListener("keydown",N),r.modalOverlay.removeEventListener("click",v),r.modalForm.removeEventListener("submit",b),r.modalForm.reset()},B=(e,t)=>{e.preventDefault();const o=e.target.elements,d=o.nodeInput.value.trim(),s=o.nodeTextarea.value.trim();if(!d||!s){p("You must fill all fields!");return}const a=l("userNodes").map(y=>y.id===t?{id:t,title:d,message:s}:y);h("userNodes",a),m(),setTimeout(()=>{i(a),u("You have successfully edit node"),g()},200),c()},S=()=>{if(!l("userNodes").length){L("Nothing to delete");return}m(),setTimeout(()=>{localStorage.removeItem("userNodes"),i(l("userNodes")),u("You have successfully deleted all nodes!"),g()},200)},E=e=>{e.preventDefault();const t=e.target.elements.searchNode.value.trim();if(!t){p("Fill fields");return}const o=l("userNodes").filter(d=>d.title===t);if(!o.length){L("Nothing to search");return}i(o),u("You have finally found your node!"),e.currentTarget.reset()},w=e=>{const o=l("userNodes").filter(d=>Number(e)!==Number(d.id));m(),setTimeout(()=>{h("userNodes",o),i(o),u("You have delete a node!"),g()},200)};document.addEventListener("DOMContentLoaded",()=>{i(l("userNodes"))});const O=({target:e})=>{e.matches("#deleteAllNodeBtn")&&S(),e.matches("#addNodeBtn")&&(r.modalOverlay.classList.add("is-open"),r.modalOverlay.addEventListener("click",v),r.modalForm.addEventListener("submit",b),document.addEventListener("keydown",N))},C=({target:e})=>{const t=e.closest("li");if(e.matches("#editNodeBtn")&&(r.modalForm.elements.nodeInput.value=t.querySelector("h3").dataset.title,r.modalForm.elements.nodeTextarea.value=t.querySelector("p").dataset.message,r.modalOverlay.classList.add("is-open"),r.modalOverlay.addEventListener("click",o=>v(o)),r.modalForm.addEventListener("submit",o=>B(o,Number(t.dataset.id))),document.addEventListener("keydown",N)),e.matches("#deleteNodeBtn")){const o=t.dataset.id;w(o)}};r.nodesList.addEventListener("click",C);r.searchForm.addEventListener("submit",E);r.headerButtons.addEventListener("click",O);
//# sourceMappingURL=index.js.map
