import{i as u}from"./assets/vendor-iVKk4foX.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const l=e=>{try{return JSON.parse(localStorage.getItem(e))||[]}catch(o){throw console.log("Something went wrong with getting all nodes!"),o}},f=(e,o)=>{try{localStorage.setItem(e,JSON.stringify(o))}catch(s){throw console.log("Something went wrong with getting all nodes!"),s}},h=e=>{u.error({iconUrl:"./img/bi_x-octagon.svg",position:"topRight",progressBarColor:"#B51B1B",message:e,messageColor:"#FAFAFB",backgroundColor:"#EF4040"})},p=e=>{u.error({iconUrl:"/img/bi_check2-circle.svg",position:"topRight",progressBarColor:"#326101",message:e,messageColor:"#FAFAFB",backgroundColor:"#59A10D"})},N=e=>{u.error({iconUrl:"./img/bi_exclamation-triangle.svg",position:"topRight",progressBarColor:"#BB7B10",message:e,messageColor:"#FAFAFB",backgroundColor:"#FFA000"})},n={headerButtons:document.querySelector(".header-btns"),modalOverlay:document.querySelector(".modal-overlay"),modalForm:document.querySelector(".modal-form"),nodesList:document.querySelector(".nodes-list"),searchForm:document.querySelector(".search-form"),loader:document.querySelector(".loader")},L=({id:e,title:o,message:s})=>`
    <li class="nodes-item" data-id="${e}">
        <h3 class="nodes-item-title">${o}</h3>
        <p class="nodes-item-description">${s}</p>
        <div class="nodes-item-btns">
          <button class="edit-node-btn" type="button" id="editNodeBtn">Edit</button>
          <button class="delete-node-btn" type="button" id="deleteNodeBtn">Delete</button>
        </div>
    </li>
  `,a=e=>{const o=e.map(L).join("");n.nodesList.innerHTML=o},m=()=>{n.loader.classList.add("is-loading")},g=()=>{n.loader.classList.remove("is-loading")},y=e=>{e.preventDefault();const o=e.target.elements,s=o.nodeInput.value.trim(),d=o.nodeTextarea.value.trim();if(!s||!d){N("Fill all fields");return}const t=l("userNodes")||0,r={id:++t.length,title:s,message:d},i=l("userNodes")||[];i.unshift(r),f("userNodes",i),m(),setTimeout(()=>{p("You added new Node!"),a(i),g()},200),c(),e.currentTarget.reset(),n.modalOverlay.removeEventListener("click",v),n.modalForm.removeEventListener("submit",y),document.removeEventListener("keydown",b)},v=e=>{e.target===e.currentTarget&&c(),e.target.matches("#modalCloseBtn")&&c()},b=e=>{e.key==="Escape"&&c()},c=()=>{n.modalOverlay.classList.remove("is-open")},B=()=>{if(!l("userNodes").length){h("Nothing to delete");return}m(),setTimeout(()=>{localStorage.removeItem("userNodes"),a(l("userNodes")),g()},200)},F=e=>{e.preventDefault();const o=e.target.elements.searchNode.value.trim();if(!o){N("Fill fields");return}const s=l("userNodes").filter(d=>d.title===o);if(!s.length){h("Nothing to search");return}a(s),p("You have finally found your node!"),e.currentTarget.reset()},S=e=>{const s=l("userNodes").filter(d=>Number(e)!==Number(d.id));m(),setTimeout(()=>{f("userNodes",s),a(s),g()},200)};document.addEventListener("DOMContentLoaded",()=>{a(l("userNodes"))});const w=({target:e})=>{e.matches("#deleteAllNodeBtn")&&B(),e.matches("#addNodeBtn")&&(n.modalOverlay.classList.add("is-open"),n.modalOverlay.addEventListener("click",v),n.modalForm.addEventListener("submit",y),document.addEventListener("keydown",b))},E=({target:e})=>{if(e.matches("#editNodeBtn")&&console.log("editNodeBtn"),e.matches("#deleteNodeBtn")){const o=e.closest("li").dataset.id;S(o)}};n.nodesList.addEventListener("click",E);n.searchForm.addEventListener("submit",F);n.headerButtons.addEventListener("click",w);
//# sourceMappingURL=index.js.map
